// 全局数据字典 (扩充版 500+)
const nameDB = [
    // === 【可爱动物】 ===
    { category: "可爱动物", name: "มด", pron: "Mod (摩)", meaning: "蚂蚁", gender: "男女通用", desc: "经典泰国小名，寓意身材娇小可爱、勤劳踏实。" },
    { category: "可爱动物", name: "นก", pron: "Nok (诺)", meaning: "鸟", gender: "男女通用", desc: "寓意像鸟儿一样自由自在、飞得高看得远。" },
    { category: "可爱动物", name: "แมว", pron: "Maew (喵)", meaning: "猫", gender: "偏向女生", desc: "现代女生常用，寓意像小猫一样温顺娇俏。" },
    { category: "可爱动物", name: "ปลาวาฬ", pron: "Pla-wan (巴湾)", meaning: "鲸鱼", gender: "偏向男生", desc: "近年来流行的大气小名，常用于微胖可爱的男孩。" },
    { category: "可爱动物", name: "หมู", pron: "Moo (姆)", meaning: "猪", gender: "男女通用", desc: "在泰国叫‘小猪’是极度亲昵的表现，代表白胖健康。" },
    { category: "可爱动物", name: "กุ้ง", pron: "Goong (恭)", meaning: "虾", gender: "男女通用", desc: "常用于个子小巧灵活的孩子。" },
    { category: "可爱动物", name: "ปลา", pron: "Pla (巴)", meaning: "鱼", gender: "男女通用", desc: "寓意如鱼得水，自由自在。" },
    { category: "可爱动物", name: "หมี", pron: "Mee (咪)", meaning: "熊", gender: "男女通用", desc: "给人憨厚、可爱、有安全感的感觉。" },
    { category: "可爱动物", name: "กระต่าย", pron: "Kra-tai (嘎带)", meaning: "兔子", gender: "偏向女生", desc: "温柔活泼，非常适合女孩子。" },
    { category: "可爱动物", name: "ช้าง", pron: "Chang (畅)", meaning: "大象", gender: "偏向男生", desc: "大象是泰国神兽，寓意强壮、稳重、有福气。" },
    { category: "可爱动物", name: "เป็ด", pron: "Ped (贝)", meaning: "鸭子", gender: "男女通用", desc: "听起来发音短促可爱，常作小名。" },
    { category: "可爱动物", name: "เสือ", pron: "Suea (素阿)", meaning: "老虎", gender: "偏向男生", desc: "寓意勇敢、威猛，充满阳刚之气。" },
    { category: "可爱动物", name: "สิงโต", pron: "Sing-to (星多)", meaning: "狮子", gender: "偏向男生", desc: "代表王者风范和领导力。" },
    { category: "可爱动物", name: "ผีเสื้อ", pron: "Pee-suea (皮素阿)", meaning: "蝴蝶", gender: "偏向女生", desc: "寓意美丽、蜕变、优雅。" },
    { category: "可爱动物", name: "เต่า", pron: "Tao (岛)", meaning: "乌龟", gender: "男女通用", desc: "在泰国文化中也有长寿、稳重的意思。" },
    { category: "可爱动物", name: "สิงห์", pron: "Sing (星)", meaning: "狮/神狮", gender: "偏向男生", desc: "充满力量与神话色彩，霸气十足。" },
    { category: "可爱动物", name: "กระทิง", pron: "Kra-ting (嘎亭)", meaning: "野牛", gender: "偏向男生", desc: "象征力量、健壮和不屈不挠。" },
    { category: "可爱动物", name: "หงส์", pron: "Hong (洪)", meaning: "天鹅", gender: "偏向女生", desc: "常用于形容女孩高贵、优雅、美丽。" },
    { category: "可爱动物", name: "นกยูง", pron: "Nok-yoong (诺勇)", meaning: "孔雀", gender: "偏向女生", desc: "寓意华丽、自信、引人注目。" },
    { category: "可爱动物", name: "ปลาทู", pron: "Pla-too (巴图)", meaning: "鲭鱼", gender: "男女通用", desc: "泰国国民美食，做小名非常接地气且可爱。" },
    { category: "可爱动物", name: "แมงปอ", pron: "Mang-por (曼波)", meaning: "蜻蜓", gender: "偏向女生", desc: "给人轻盈、灵动、活泼的印象。" },
    { category: "可爱动物", name: "กวาง", pron: "Kwang (光)", meaning: "鹿", gender: "偏向女生", desc: "形容女孩眼睛明亮、气质温婉。" },
    { category: "可爱动物", name: "ปู", pron: "Poo (布)", meaning: "螃蟹", gender: "男女通用", desc: "简短好记，是非常经典的传统小名。" },
    { category: "可爱动物", name: "จิ้งจอก", pron: "Jing-jok (静角)", meaning: "狐狸", gender: "偏向男生", desc: "寓意聪明、机智、反应快。" },
    { category: "可爱动物", name: "โลมา", pron: "Lo-ma (罗马)", meaning: "海豚", gender: "男女通用", desc: "象征友善、聪明、充满海洋气息。" },
    { category: "可爱动物", name: "ฉลาม", pron: "Cha-lam (查蓝)", meaning: "鲨鱼", gender: "偏向男生", desc: "给人感觉敏捷、酷炫、具有攻击性。" },
    { category: "可爱动物", name: "ไก่", pron: "Gai (盖)", meaning: "鸡", gender: "男女通用", desc: "泰国老一辈非常爱用的小名，朴实无华。" },
    { category: "可爱动物", name: "หนู", pron: "Noo (努)", meaning: "老鼠", gender: "偏向女生", desc: "在泰语中也常作为晚辈的自称，极其娇小惹人爱。" },
    { category: "可爱动物", name: "ค้างคาว", pron: "Kang-kao (康靠)", meaning: "蝙蝠", gender: "偏向男生", desc: "独特且少见，带有神秘感。" },

    // === 【甜美水果与食物】 ===
    { category: "甜美水果与食物", name: "แตงโม", pron: "Tang-mo (丹摩)", meaning: "西瓜", gender: "偏向女生", desc: "非常家喻户晓的女孩小名，给人甜美、清爽的感觉。" },
    { category: "甜美水果与食物", name: "ส้ม", pron: "Som (颂)", meaning: "橙子/橘子", gender: "偏向女生", desc: "寓意大吉大利、酸甜可爱。" },
    { category: "甜美水果与食物", name: "ชมพู่", pron: "Chom-phoo (崇普)", meaning: "莲雾", gender: "偏向女生", desc: "自带时尚感与名媛甜美风。" },
    { category: "甜美水果与食物", name: "แอปเปิ้ล", pron: "Apple (苹果)", meaning: "苹果", gender: "偏向女生", desc: "受西方影响，水果英文发音做小名显得很洋气。" },
    { category: "甜美水果与食物", name: "เชอร์รี่", pron: "Cherry (樱桃)", meaning: "樱桃", gender: "偏向女生", desc: "娇小可爱，充满元气。" },
    { category: "甜美水果与食物", name: "กล้วย", pron: "Kluay (柜伊)", meaning: "香蕉", gender: "男女通用", desc: "在泰语中也有‘简单、容易’的引申义，寓意一生顺遂。" },
    { category: "甜美水果与食物", name: "มะนาว", pron: "Ma-nao (玛瑙)", meaning: "柠檬", gender: "偏向女生", desc: "形容性格活泼、带点小脾气的可爱女孩。" },
    { category: "甜美水果与食物", name: "ข้าวหอม", pron: "Khao-hom (靠洪)", meaning: "茉莉香米", gender: "偏向女生", desc: "非常传统且美好的名字，寓意珍贵、芬芳。" },
    { category: "甜美水果与食物", name: "น้ำตาล", pron: "Nam-tan (南丹)", meaning: "糖", gender: "偏向女生", desc: "寓意生活甜甜蜜蜜，性格惹人喜爱。" },
    { category: "甜美水果与食物", name: "เค้ก", pron: "Cake (蛋糕)", meaning: "蛋糕", gender: "偏向女生", desc: "现代流行小名，甜蜜可爱。" },
    { category: "甜美水果与食物", name: "แพนเค้ก", pron: "Pancake (煎饼)", meaning: "煎饼", gender: "偏向女生", desc: "因为某位著名泰国女星而爆火的名字。" },
    { category: "甜美水果与食物", name: "พีช", pron: "Peach (桃子)", meaning: "桃子", gender: "男女通用", desc: "年轻人非常喜欢的洋气水果名。" },
    { category: "甜美水果与食物", name: "คุกกี้", pron: "Cookie (曲奇)", meaning: "曲奇饼干", gender: "偏向女生", desc: "受西方烘焙文化影响，听起来酥脆香甜。" },
    { category: "甜美水果与食物", name: "เนย", pron: "Noey (诺伊)", meaning: "黄油", gender: "偏向女生", desc: "非常经典的甜美女孩名，如同黄油般细腻柔滑。" },
    { category: "甜美水果与食物", name: "สเต็ก", pron: "Steak (牛排)", meaning: "牛排", gender: "偏向男生", desc: "现代饮食文化衍生出的小名，带有一丝硬朗和洋气。" },
    { category: "甜美水果与食物", name: "นมสด", pron: "Nom-sod (农搜)", meaning: "鲜奶", gender: "偏向女生", desc: "给人感觉纯洁、营养、白嫩。" },
    { category: "甜美水果与食物", name: "แยม", pron: "Yam (燕)", meaning: "果酱", gender: "偏向女生", desc: "甜美可人，发音简单好听。" },
    { category: "甜美水果与食物", name: "ขิง", pron: "Khing (晴)", meaning: "生姜", gender: "偏向女生", desc: "短促有力，偶尔用于形容带点辛辣个性的女生。" },
    { category: "甜美水果与食物", name: "พาย", pron: "Pie (派)", meaning: "派", gender: "偏向女生", desc: "西式烘焙甜品，发音温柔。" },
    { category: "甜美水果与食物", name: "โดนัท", pron: "Donut (多纳)", meaning: "甜甜圈", gender: "偏向女生", desc: "圆润可爱的代名词。" },
    { category: "甜美水果与食物", name: "ชาบู", pron: "Shabu (呷哺)", meaning: "日式火锅", gender: "男女通用", desc: "吃货家庭特别喜欢的现代趣味小名。" },
    { category: "甜美水果与食物", name: "กาแฟ", pron: "Ga-fae (咖啡)", meaning: "咖啡", gender: "偏向男生", desc: "带有醇厚、成熟的气息。" },
    { category: "甜美水果与食物", name: "มะลิ", pron: "Ma-li (玛丽)", meaning: "茉莉花", gender: "偏向女生", desc: "泰国的母亲之花，纯洁芬芳。" },
    { category: "甜美水果与食物", name: "ข้าวโพด", pron: "Khao-pod (靠珀)", meaning: "玉米", gender: "男女通用", desc: "金灿灿的，给人丰收喜悦的感觉。" },

    // === 【自然与宝石】 ===
    { category: "自然与宝石", name: "พลอย", pron: "Ploy (坡loy)", meaning: "宝石", gender: "偏向女生", desc: "极其经典且高雅的女孩名，寓意像珍宝一样被珍视。" },
    { category: "自然与宝石", name: "เพชร", pron: "Petch (佩)", meaning: "钻石", gender: "偏向男生", desc: "寓意坚强不屈、璀璨夺目，常用于男孩子。" },
    { category: "自然与宝石", name: "ฟ้า", pron: "Fah (发)", meaning: "天空", gender: "偏向女生", desc: "寓意心胸如天空般广阔纯洁，给人温柔、宁静的感觉。" },
    { category: "自然与宝石", name: "ฝน", pron: "Fon (丰)", meaning: "雨", gender: "偏向女生", desc: "常给下雨天出生的孩子取名，寓意滋润万物。" },
    { category: "自然与宝石", name: "น้ำ", pron: "Nam (男)", meaning: "水", gender: "男女通用", desc: "寓意温柔、包容、财富如水连绵不绝。" },
    { category: "自然与宝石", name: "ดาว", pron: "Dao (道)", meaning: "星星", gender: "偏向女生", desc: "寓意闪闪发光，是人群中的焦点。" },
    { category: "自然与宝石", name: "เดือน", pron: "Duean (杜恩)", meaning: "月亮/月份", gender: "偏向女生", desc: "传统且富有诗意的小名。" },
    { category: "自然与宝石", name: "ตะวัน", pron: "Ta-wan (达湾)", meaning: "太阳", gender: "男女通用", desc: "寓意阳光灿烂、充满希望与生命力。" },
    { category: "自然与宝石", name: "ซัน", pron: "Sun (桑)", meaning: "太阳(英文)", gender: "偏向男生", desc: "Tawan的现代英文版，非常受男孩家庭欢迎。" },
    { category: "自然与宝石", name: "เมฆ", pron: "Mek (麦)", meaning: "云", gender: "偏向男生", desc: "给人自由、无拘无束的感觉。" },
    { category: "自然与宝石", name: "หยก", pron: "Yok (哟)", meaning: "玉", gender: "偏向女生", desc: "受华人文化影响，寓意高洁、平安。" },
    { category: "自然与宝石", name: "มุก", pron: "Mook (木)", meaning: "珍珠", gender: "偏向女生", desc: "寓意纯洁无瑕，是非常优雅的女孩名。" },
    { category: "自然与宝石", name: "ทะเล", pron: "Ta-lay (塔雷)", meaning: "大海", gender: "男女通用", desc: "近年来流行的文艺向小名。" },
    { category: "自然与宝石", name: "ทราย", pron: "Sai (赛)", meaning: "沙子", gender: "偏向女生", desc: "经典泰国名字，给人温柔细腻的印象。" },
    { category: "自然与宝石", name: "ภูผา", pron: "Phu-pha (普帕)", meaning: "高山", gender: "偏向男生", desc: "寓意像大山一样稳重、坚固、有依靠。" },
    { category: "自然与宝石", name: "ธาร", pron: "Tarn (坦)", meaning: "溪流", gender: "男女通用", desc: "给人清凉、绵延不绝的诗意感。" },
    { category: "自然与宝石", name: "ดิน", pron: "Din (丁)", meaning: "泥土", gender: "偏向男生", desc: "踏实、接地气，代表生命的根基。" },
    { category: "自然与宝石", name: "หิน", pron: "Hin (欣)", meaning: "石头", gender: "偏向男生", desc: "象征坚硬、顽强。" },
    { category: "自然与宝石", name: "พายุ", pron: "Pha-yu (帕尤)", meaning: "风暴", gender: "偏向男生", desc: "充满力量与动感，霸气侧漏。" },
    { category: "自然与宝石", name: "สกาย", pron: "Sky (斯凯)", meaning: "天空", gender: "男女通用", desc: "Fah 的洋气英文版，年轻人爱用。" },
    { category: "自然与宝石", name: "สโนว์", pron: "Snow (斯诺)", meaning: "雪", gender: "偏向女生", desc: "泰国虽然不下雪，但这不影响父母对纯洁白雪的向往。" },
    { category: "自然与宝石", name: "ซัมเมอร์", pron: "Summer (夏默)", meaning: "夏天", gender: "偏向女生", desc: "充满活力与阳光的季节名。" },
    { category: "自然与宝石", name: "เงิน", pron: "Ngoen (恩)", meaning: "银", gender: "偏向男生", desc: "传统的财富象征。" },
    { category: "自然与宝石", name: "ทอง", pron: "Thong (通)", meaning: "金", gender: "偏向男生", desc: "泰国最经典的带财气小名，代表尊贵。" },

    // === 【现代洋气 (含汽车、IT科技与外语)】 ===
    { category: "现代洋气", name: "บอล", pron: "Ball (波)", meaning: "球", gender: "偏向男生", desc: "非常普遍的男孩子小名，寓意热爱运动、开朗。" },
    { category: "现代洋气", name: "แบงก์", pron: "Bank (班)", meaning: "银行", gender: "偏向男生", desc: "泰国人喜欢用财富相关的英文做小名，寓意财源滚滚。" },
    { category: "现代洋气", name: "กิ๊ฟ", pron: "Gift (技发)", meaning: "礼物", gender: "偏向女生", desc: "寓意孩子是上天赐予最珍贵的礼物。" },
    { category: "现代洋气", name: "มิ้นท์", pron: "Mint (敏)", meaning: "薄荷", gender: "偏向女生", desc: "给人清新自然、充满时尚气息的印象。" },
    { category: "现代洋气", name: "มายด์", pron: "Mind (迈)", meaning: "心智/思想", gender: "偏向女生", desc: "非常流行的女孩名字，听起来聪明伶俐。" },
    { category: "现代洋气", name: "ไอซ์", pron: "Ice (艾斯)", meaning: "冰", gender: "男女通用", desc: "听起来很酷的名字。" },
    { category: "现代洋气", name: "นิว", pron: "New (纽)", meaning: "新", gender: "男女通用", desc: "寓意新生命的到来、新的希望。" },
    { category: "现代洋气", name: "โฟกัส", pron: "Focus (佛卡)", meaning: "焦点", gender: "男女通用", desc: "父母希望孩子做任何事都能专心致志。" },
    { category: "现代洋气", name: "บอส", pron: "Boss (波斯)", meaning: "老板", gender: "偏向男生", desc: "寄托了父母希望孩子未来事业有成的期望。" },
    { category: "现代洋气", name: "แชมป์", pron: "Champ (强)", meaning: "冠军", gender: "偏向男生", desc: "寓意永远做第一名，充满胜负欲与进取心。" },
    { category: "现代洋气", name: "คิง", pron: "King (金)", meaning: "国王", gender: "偏向男生", desc: "大气、尊贵的名字。" },
    { category: "现代洋气", name: "กีต้าร์", pron: "Guitar (吉他)", meaning: "吉他", gender: "男女通用", desc: "带有艺术气息，热爱音乐的家庭首选。" },
    { category: "现代洋气", name: "ไวน์", pron: "Wine (瓦伊)", meaning: "葡萄酒", gender: "偏向女生", desc: "听起来高贵优雅且时尚。" },
    { category: "现代洋气", name: "เบนซ์", pron: "Benz (本兹)", meaning: "奔驰", gender: "男女通用", desc: "泰国人非常喜欢用汽车品牌做小名，寓意富有和品位。" },
    { category: "现代洋气", name: "ฟอร์ด", pron: "Ford (福特)", meaning: "福特", gender: "偏向男生", desc: "受美系汽车文化影响，带有硬派、工程和机械感。" },
    { category: "现代洋气", name: "พอร์ช", pron: "Porsche (保时捷)", meaning: "保时捷", gender: "偏向男生", desc: "超级跑车品牌，代表速度、奢华与激情。" },
    { category: "现代洋气", name: "มินิ", pron: "Mini (迷你)", gender: "偏向女生", meaning: "Mini汽车", desc: "娇小可爱，时尚感拉满的车系小名。" },
    { category: "现代洋气", name: "แม็ค", pron: "Mac (麦克)", meaning: "Mac电脑/苹果", gender: "偏向男生", desc: "受极客和科技生态影响诞生的洋气小名。" },
    { category: "现代洋气", name: "แม็กซ์", pron: "Max (麦克斯)", meaning: "最大/极限", gender: "偏向男生", desc: "寓意做到极致，追求完美。" },
    { category: "现代洋气", name: "ออโต้", pron: "Auto (奥拓)", meaning: "自动/机械", gender: "偏向男生", desc: "充满理工科和工业机械浪漫的小名。" },
    { category: "现代洋气", name: "กอล์ฟ", pron: "Golf (高尔夫)", meaning: "高尔夫球", gender: "偏向男生", desc: "泰国极为普及的男士小名，代表优雅的高级运动。" },
    { category: "现代洋气", name: "เทอร์โบ", pron: "Turbo (涡轮)", meaning: "涡轮增压", gender: "偏向男生", desc: "听起来就马力十足，活力四射。" },
    { category: "现代洋气", name: "ยูกิ", pron: "Yuki (尤基)", meaning: "雪(日文)", gender: "偏向女生", desc: "受日本文化深远影响，许多泰国人喜欢取日系小名。" },
    { category: "现代洋气", name: "เคน", pron: "Ken (肯)", meaning: "健(日文)", gender: "偏向男生", desc: "日系经典男名，在泰国认知度极高。" },
    { category: "现代洋气", name: "โซดา", pron: "Soda (苏打)", meaning: "苏打水", gender: "偏向女生", desc: "清爽冒泡，年轻一代的热门选择。" },
    { category: "现代洋气", name: "เกมส์", pron: "Game (盖姆)", meaning: "游戏", gender: "偏向男生", desc: "寓意人生如一场充满挑战的游戏。" },
    { category: "现代洋气", name: "เบส", pron: "Best (贝斯特)", meaning: "最好", gender: "男女通用", desc: "希望孩子成为最棒的那一个。" },
    { category: "现代洋气", name: "ไนซ์", pron: "Nice (奈斯)", meaning: "美好", gender: "男女通用", desc: "性格和善，惹人喜爱。" },
    { category: "现代洋气", name: "พีซี", pron: "PC (皮西)", meaning: "个人电脑", gender: "偏向男生", desc: "科技硬件迷父母最爱的硬核小名。" },

    // === 【颜色与外貌】 ===
    { category: "颜色与外貌", name: "แดง", pron: "Dang (当)", meaning: "红色", gender: "男女通用", desc: "泰国最传统的小名之一，喜庆且充满活力。" },
    { category: "颜色与外貌", name: "ดำ", pron: "Dum (丹)", meaning: "黑色", gender: "偏向男生", desc: "过去常用来给皮肤偏黑的孩子取名，带有一种健康淳朴感。" },
    { category: "颜色与外貌", name: "ขาว", pron: "Khao (靠)", meaning: "白色", gender: "男女通用", desc: "形容孩子皮肤白皙纯净。" },
    { category: "颜色与外貌", name: "ชมพู", pron: "Chom-poo (冲普)", meaning: "粉色", gender: "偏向女生", desc: "充满少女心，温柔甜美。" },
    { category: "颜色与外貌", name: "บลู", pron: "Blue (布鲁)", meaning: "蓝色", gender: "男女通用", desc: "现代父母爱用的颜色英文，忧郁或宁静。" },
    { category: "颜色与外貌", name: "อ้วน", pron: "Ouan (万)", meaning: "胖", gender: "男女通用", desc: "在泰国叫‘胖胖’完全没有贬义，是长辈对肉嘟嘟孩子的爱称。" },
    { category: "颜色与外貌", name: "เล็ก", pron: "Lek (雷)", meaning: "小", gender: "男女通用", desc: "家里最小的孩子经常叫这个，寓意娇小可爱。" },
    { category: "颜色与外貌", name: "ใหญ่", pron: "Yai (崖)", meaning: "大", gender: "偏向男生", desc: "常作为长子的名字，代表能承担重任。" },
    { category: "颜色与外貌", name: "หมวย", pron: "Muay (妹)", meaning: "华人女孩", gender: "偏向女生", desc: "源自潮汕话，形容具有华裔特征（单眼皮、白皮肤）的漂亮女孩。" },
    { category: "颜色与外貌", name: "ตี๋", pron: "Tee (弟)", meaning: "华人男孩", gender: "偏向男生", desc: "源自潮汕话，形容清秀白净的华裔血统男孩。" },
    { category: "颜色与外貌", name: "นุ่น", pron: "Noon (暖)", meaning: "木棉", gender: "偏向女生", desc: "形容像木棉花絮一样柔软、轻盈。" },

    // === 【传统祈福与品质】 ===
    { category: "传统祈福与品质", name: "โชค", pron: "Chok (丘)", meaning: "运气", gender: "偏向男生", desc: "带来好运和福气。" },
    { category: "传统祈福与品质", name: "เก่ง", pron: "Keng (耿)", meaning: "聪明/能干", gender: "偏向男生", desc: "父母对孩子才华和能力的直接期许。" },
    { category: "传统祈福与品质", name: "ดี", pron: "Dee (迪)", meaning: "好", gender: "男女通用", desc: "简单纯粹，寓意一切顺利美好。" },
    { category: "传统祈福与品质", name: "จริงใจ", pron: "Jing-jai (晶载)", meaning: "真诚", gender: "偏向女生", desc: "代表拥有一颗诚实、坦率的心。" },
    { category: "传统祈福与品质", name: "รวย", pron: "Ruay (瑞)", meaning: "富有", gender: "男女通用", desc: "朴实无华的暴富祈愿。" },
    { category: "传统祈福与品质", name: "เฮง", pron: "Heng (亨)", meaning: "旺/好运", gender: "偏向男生", desc: "受华人文化影响，“兴旺”之意，做生意家庭最爱。" },
    { category: "传统祈福与品质", name: "กล้า", pron: "Kla (格拉)", meaning: "勇敢", gender: "偏向男生", desc: "无所畏惧，男子汉的象征。" },
    { category: "传统祈福与品质", name: "รัก", pron: "Rak (拉)", meaning: "爱", gender: "男女通用", desc: "被爱包围，同时也懂得爱人。" },
    { category: "传统祈福与品质", name: "ยิ้ม", pron: "Yim (印)", meaning: "微笑", gender: "偏向女生", desc: "泰国是‘微笑之国’，这名字代表乐观开朗。" },
    { category: "传统祈福与品质", name: "สุข", pron: "Suk (素)", meaning: "幸福/快乐", gender: "男女通用", desc: "一生平安喜乐。" },
    { category: "传统祈福与品质", name: "ขวัญ", pron: "Kwan (宽)", meaning: "灵魂/礼物", gender: "偏向女生", desc: "非常古典的泰语，指代精神上的珍宝。" },
    { category: "传统祈福与品质", name: "บุญ", pron: "Boon (汶)", meaning: "功德/福报", gender: "偏向男生", desc: "佛教文化背景下最神圣的名字之一。" }, // 注意这里补上了逗号！

    // === 【可爱动物 (扩充)】 ===
    { category: "可爱动物", name: "ผึ้ง", pron: "Pueng (朋)", meaning: "蜜蜂", gender: "偏向女生", desc: "寓意勤劳、甜美、能带来财富。" },
    { category: "可爱动物", name: "แพนด้า", pron: "Panda (潘达)", meaning: "熊猫", gender: "男女通用", desc: "非常受年轻人欢迎，听起来憨态可掬。" },
    { category: "可爱动物", name: "นกฮูก", pron: "Nok-hook (诺胡)", meaning: "猫头鹰", gender: "男女通用", desc: "在某些语境下代表智慧和敏锐。" },
    { category: "可爱动物", name: "ม้า", pron: "Ma (玛)", meaning: "马", gender: "偏向男生", desc: "寓意奔放、自由、马到成功。" },
    { category: "可爱动物", name: "ไดโน", pron: "Dino (迪诺)", meaning: "恐龙", gender: "偏向男生", desc: "男孩子们特别喜欢的小名，充满童趣与力量。" },
    { category: "可爱动物", name: "เพนกวิน", pron: "Penguin (企鹅)", meaning: "企鹅", gender: "男女通用", desc: "洋气且可爱，常用于性格温和的孩子。" },
    { category: "可爱动物", name: "จ๋อ", pron: "Jor (卓)", meaning: "小猴子", gender: "男女通用", desc: "极其调皮可爱的爱称，形容像猴子一样机灵。" },
    { category: "可爱动物", name: "กบ", pron: "Gop (果)", meaning: "青蛙", gender: "男女通用", desc: "泰国老一辈爱用的小名，非常传统、接地气。" },
    { category: "可爱动物", name: "หอย", pron: "Hoi (海)", meaning: "贝壳", gender: "男女通用", desc: "带有海洋气息的传统小名。" },
    { category: "可爱动物", name: "หนอน", pron: "Nhon (农)", meaning: "毛毛虫", gender: "男女通用", desc: "听起来软绵绵的，常作为极其亲昵的婴儿小名。" },
    { category: "可爱动物", name: "ชีต้า", pron: "Cheetah (猎豹)", meaning: "猎豹", gender: "偏向男生", desc: "速度与爆发力的象征，非常酷炫。" },

    // === 【甜美水果与食物 (扩充)】 ===
    { category: "甜美水果与食物", name: "ซูชิ", pron: "Sushi (寿司)", meaning: "寿司", gender: "男女通用", desc: "受日本饮食文化影响诞生的可爱小名。" },
    { category: "甜美水果与食物", name: "โมจิ", pron: "Mochi (麻薯)", meaning: "麻薯", gender: "偏向女生", desc: "形容女孩脸颊像麻薯一样软糯可爱。" },
    { category: "甜美水果与食物", name: "ช็อกโก้", pron: "Choco (巧可)", meaning: "巧克力", gender: "男女通用", desc: "甜美、浓郁，常用于肤色健康的孩子。" },
    { category: "甜美水果与食物", name: "โกโก้", pron: "Cocoa (可可)", meaning: "可可", gender: "男女通用", desc: "发音圆润好听。" },
    { category: "甜美水果与食物", name: "มาม่า", pron: "Mama (玛玛)", meaning: "方便面", gender: "男女通用", desc: "泰国国民泡面品牌，做小名非常有个性。" },
    { category: "甜美水果与食物", name: "พริก", pron: "Prik (普里)", meaning: "辣椒", gender: "偏向女生", desc: "寓意性格火辣、直爽、不好惹的个性女孩。" },
    { category: "甜美水果与食物", name: "ซีอิ๊ว", pron: "Si-iw (西尤)", meaning: "酱油", gender: "男女通用", desc: "受华人文化影响，很有家庭烟火气的小名。" },
    { category: "甜美水果与食物", name: "พะโล้", pron: "Pa-lo (帕洛)", meaning: "卤肉", gender: "偏向男生", desc: "给人一种圆润、香气四溢的可爱感。" },
    { category: "甜美水果与食物", name: "ชีส", pron: "Cheese (芝士)", meaning: "芝士", gender: "男女通用", desc: "现代流行，拉丝的香甜与洋气。" },
    { category: "甜美水果与食物", name: "น้ำปั่น", pron: "Nam-pan (南班)", meaning: "冰沙", gender: "偏向女生", desc: "清凉解暑，充满夏日气息。" },
    { category: "甜美水果与食物", name: "ปอนด์", pron: "Pond (磅)", meaning: "磅蛋糕/英镑", gender: "偏向男生", desc: "既可以指蛋糕，也有英镑财富的含义，非常普遍。" },
    { category: "甜美水果与食物", name: "ข้าวกล้อง", pron: "Khao-glong (靠弓)", meaning: "糙米", gender: "男女通用", desc: "传统农耕文化的体现，代表健康、质朴。" },
    { category: "甜美水果与食物", name: "องุ่น", pron: "A-ngun (阿滚)", meaning: "葡萄", gender: "偏向女生", desc: "酸甜可口，小巧精致。" },
    { category: "甜美水果与食物", name: "เงาะ", pron: "Ngo (哦)", meaning: "红毛丹", gender: "男女通用", desc: "泰国经典水果，做小名充满本土风情。" },

    // === 【植物与花卉】 ===
    { category: "植物与花卉", name: "ใบเตย", pron: "Bai-toey (拜登)", meaning: "斑斓叶", gender: "偏向女生", desc: "泰国甜品中最常用的香料叶，自带清香与甜美。" },
    { category: "植物与花卉", name: "บัว", pron: "Bua (布阿)", meaning: "莲花", gender: "偏向女生", desc: "佛教圣物，代表出淤泥而不染的纯洁。" },
    { category: "植物与花卉", name: "โรส", pron: "Rose (罗斯)", meaning: "玫瑰", gender: "偏向女生", desc: "浪漫、高贵、充满女性魅力。" },
    { category: "植物与花卉", name: "ลิลลี่", pron: "Lily (莉莉)", meaning: "百合", gender: "偏向女生", desc: "纯真无邪，非常受欢迎的外来花卉名。" },
    { category: "植物与花卉", name: "ไผ่", pron: "Pai (派)", meaning: "竹子", gender: "偏向男生", desc: "寓意像竹子一样坚韧不拔、节节高升。" },
    { category: "植物与花卉", name: "ต้นไม้", pron: "Ton-mai (东麦)", meaning: "树木", gender: "偏向男生", desc: "给人茁壮成长、生机勃勃的感觉。" },
    { category: "植物与花卉", name: "หญ้า", pron: "Ya (雅)", meaning: "小草", gender: "偏向女生", desc: "生命力顽强，春风吹又生。" },
    { category: "植物与花卉", name: "ต้นกล้า", pron: "Ton-kla (东格拉)", meaning: "幼苗", gender: "偏向男生", desc: "代表希望、新生与未来的栋梁。" },
    { category: "植物与花卉", name: "เฟิร์น", pron: "Fern (芬)", meaning: "蕨类植物", gender: "偏向女生", desc: "绿意盎然，非常流行的森系女孩名。" },
    { category: "植物与花卉", name: "มะกอก", pron: "Ma-gok (玛果)", meaning: "橄榄", gender: "男女通用", desc: "传统且带有和平、长寿的寓意。" },
    { category: "植物与花卉", name: "แครอท", pron: "Carrot (胡萝卜)", meaning: "胡萝卜", gender: "男女通用", desc: "听起来清脆有活力。" },
    { category: "植物与花卉", name: "ดอกไม้", pron: "Dok-mai (朵麦)", meaning: "花朵", gender: "偏向女生", desc: "最直白的赞美，如花般美丽。" },

    // === 【自然与宝石 (扩充)】 ===
    { category: "自然与宝石", name: "รุ้ง", pron: "Roong (荣)", meaning: "彩虹", gender: "偏向女生", desc: "雨后彩虹，代表绚烂、美好与希望。" },
    { category: "自然与宝石", name: "คลื่น", pron: "Kluen (克伦)", meaning: "波浪", gender: "偏向男生", desc: "充满动感，象征无穷的能量。" },
    { category: "自然与宝石", name: "เอิร์ท", pron: "Earth (厄斯)", meaning: "地球", gender: "偏向男生", desc: "非常有格局的名字，包容万物。" },
    { category: "自然与宝石", name: "มาร์ส", pron: "Mars (马斯)", meaning: "火星", gender: "偏向男生", desc: "带有一点科幻与战神色彩。" },
    { category: "自然与宝石", name: "วีนัส", pron: "Venus (维纳斯)", meaning: "金星", gender: "偏向女生", desc: "爱与美的女神，高贵优雅。" },
    { category: "自然与宝石", name: "พลูโต", pron: "Pluto (普鲁托)", meaning: "冥王星", gender: "男女通用", desc: "小众且充满宇宙浪漫。" },
    { category: "自然与宝石", name: "แซนด์", pron: "Sand (散)", meaning: "沙", gender: "男女通用", desc: "Sai(沙子) 的洋气英文版本。" },
    { category: "自然与宝石", name: "ออโรร่า", pron: "Aurora (极光)", meaning: "极光", gender: "偏向女生", desc: "绚丽夺目，仙气飘飘的现代名。" },
    { category: "自然与宝石", name: "สปาร์ค", pron: "Spark (斯巴)", meaning: "火花", gender: "偏向男生", desc: "一触即发，精力充沛。" },

    // === 【日常生活与物品】 ===
    { category: "日常生活与物品", name: "แสตมป์", pron: "Stamp (斯丹)", meaning: "邮票", gender: "男女通用", desc: "泰国人非常爱用的经典物品名，见证远方与情谊。" },
    { category: "日常生活与物品", name: "ตั๋ว", pron: "Tua (朵)", meaning: "票", gender: "男女通用", desc: "寓意通往各个美好地方的通行证。" },
    { category: "日常生活与物品", name: "เพลง", pron: "Pleng (普楞)", meaning: "歌曲", gender: "偏向女生", desc: "充满文艺气息，如同一首美妙的歌。" },
    { category: "日常生活与物品", name: "โน้ต", pron: "Note (诺特)", meaning: "音符/笔记", gender: "偏向男生", desc: "文静或者热爱音乐的男孩子常用。" },
    { category: "日常生活与物品", name: "ไมค์", pron: "Mike (麦克风)", meaning: "麦克风", gender: "偏向男生", desc: "勇敢表达自我，也有英文名Mike的双重含义。" },
    { category: "日常生活与物品", name: "เข็ม", pron: "Kem (肯)", meaning: "针", gender: "偏向女生", desc: "形容女孩心思细腻、尖锐敏锐。" },
    { category: "日常生活与物品", name: "ด้าย", pron: "Dai (代)", meaning: "线", gender: "偏向女生", desc: "常和‘针(Kem)’凑成双胞胎名字，寓意连结。" },
    { category: "日常生活与物品", name: "กระเป๋า", pron: "Gra-pao (嘎包)", meaning: "包包", gender: "男女通用", desc: "非常日常，有时候引申为‘钱包’，寓意有钱。" },
    { category: "日常生活与物品", name: "แอร์", pron: "Air (艾尔)", meaning: "空调/空乘", gender: "偏向女生", desc: "在泰国很流行，给人带来清凉或者向往蓝天。" },
    { category: "日常生活与物品", name: "ปืน", pron: "Peun (奔)", meaning: "枪", gender: "偏向男生", desc: "泰国男生经典小名，代表男子气概与保护欲。" },
    { category: "日常生活与物品", name: "หมอน", pron: "Mhon (蒙)", meaning: "枕头", gender: "男女通用", desc: "给人柔软、安心、想睡觉的可爱感。" },
    { category: "日常生活与物品", name: "เตียง", pron: "Tiang (丁)", meaning: "床", gender: "男女通用", desc: "温暖的避风港。" },
    { category: "日常生活与物品", name: "ภาพ", pron: "Pap (帕)", meaning: "画/照片", gender: "偏向女生", desc: "记录美好瞬间，充满艺术感。" },
    { category: "日常生活与物品", name: "กล้อง", pron: "Glong (贡)", meaning: "相机", gender: "偏向男生", desc: "现代人喜爱的物品，捕捉美好。" },
    
    // === 【现代洋气 / 品牌与地点 (扩充)】 ===
    { category: "现代洋气", name: "โบนัส", pron: "Bonus (博纳斯)", meaning: "奖金", gender: "男女通用", desc: "泰国人极其爱用，寓意孩子是上天赐予的额外奖励。" },
    { category: "现代洋气", name: "กูเกิล", pron: "Google (谷歌)", meaning: "Google", gender: "偏向男生", desc: "互联网时代诞生的名字，寓意无所不知、聪明绝顶。" },
    { category: "现代洋气", name: "แอป", pron: "App (艾普)", meaning: "App软件", gender: "男女通用", desc: "科技感十足的超现代小名。" },
    { category: "现代洋气", name: "โซนี่", pron: "Sony (索尼)", meaning: "索尼", gender: "男女通用", desc: "影音与科技发烧友家庭的常见选择。" },
    { category: "现代洋气", name: "ออดี้", pron: "Audi (奥迪)", meaning: "奥迪", gender: "偏向男生", desc: "汽车品牌，代表有品位、高端。" },
    { category: "现代洋气", name: "ปอร์เช่", pron: "Porsche (保时捷)", meaning: "保时捷", gender: "偏向男生", desc: "速度与激情的象征。" },
    { category: "现代洋气", name: "ชาแนล", pron: "Chanel (香奈儿)", meaning: "香奈儿", gender: "偏向女生", desc: "极致优雅与奢侈，富养女儿的首选。" },
    { category: "现代洋气", name: "คาร์เทียร์", pron: "Cartier (卡地亚)", meaning: "卡地亚", gender: "偏向女生", desc: "珠宝名牌，如同掌上明珠。" },
    { category: "现代洋气", name: "ลอนดอน", pron: "London (伦敦)", meaning: "伦敦", gender: "男女通用", desc: "用地名做小名很流行，带有一种英伦贵族气。" },
    { category: "现代洋气", name: "ปารีส", pron: "Paris (巴黎)", meaning: "巴黎", gender: "偏向女生", desc: "浪漫之都，时尚与美丽的化身。" },
    { category: "现代洋气", name: "โรม", pron: "Rome (罗马)", meaning: "罗马", gender: "偏向男生", desc: "宏伟、历史悠久、充满帝国气场。" },
    { category: "现代洋气", name: "ยูโร", pron: "Euro (欧元)", meaning: "欧元", gender: "偏向男生", desc: "与财富相关，听起来也很大气。" },
    { category: "现代洋气", name: "ดอลลาร์", pron: "Dollar (美元)", meaning: "美元", gender: "偏向男生", desc: "最直接的财富象征，非常洋气。" },
    { category: "现代洋气", name: "เลเซอร์", pron: "Laser (雷射)", meaning: "激光", gender: "偏向男生", desc: "精准、快速、充满未来科技感。" },
    { category: "现代洋气", name: "แฟลช", pron: "Flash (闪电侠)", meaning: "闪光", gender: "偏向男生", desc: "极速、亮眼。" },
    { category: "现代洋气", name: "นีออน", pron: "Neon (霓虹)", meaning: "霓虹灯", gender: "男女通用", desc: "赛博朋克风，在人群中闪耀。" }, // 注意这里补上了逗号！

    // === 【叠音与可爱拟声】 ===
    { category: "叠音与可爱拟声", name: "เปาเปา", pron: "Pao-pao (包包)", meaning: "包子", gender: "男女通用", desc: "非常著名的童星小名，形容脸蛋像包子一样圆润可爱。" },
    { category: "叠音与可爱拟声", name: "ปิงปอง", pron: "Ping-pong (乒乓)", meaning: "乒乓球", gender: "男女通用", desc: "清脆响亮，充满活力。" },
    { category: "叠音与可爱拟声", name: "จีจี้", pron: "Gigi (吉吉)", meaning: "Gigi", gender: "偏向女生", desc: "洋气且俏皮的女孩叠音名。" },
    { category: "叠音与可爱拟声", name: "มีมี่", pron: "Mimi (咪咪)", meaning: "Mimi", gender: "偏向女生", desc: "如同小猫一般的娇嗔可爱。" },
    { category: "叠音与可爱拟声", name: "นานา", pron: "Nana (娜娜)", meaning: "各种/Nana", gender: "偏向女生", desc: "好听易记，在多种语言中都有美好的含义。" },
    { category: "叠音与可爱拟声", name: "เจเจ", pron: "JJ (杰杰)", meaning: "字母JJ", gender: "偏向男生", desc: "酷男孩常用的首字母缩写叠音。" },
    { category: "叠音与可爱拟声", name: "ดีดี้", pron: "Didi (迪迪)", meaning: "好极了", gender: "偏向女生", desc: "谐音泰语的“好(Dee)”，寓意非常好。" },
    { category: "叠音与可爱拟声", name: "แบมแบม", pron: "Bam-bam (斑斑)", meaning: "碎石声", gender: "男女通用", desc: "因某位著名泰国偶像而火遍全球的小名。" },
    { category: "叠音与可爱拟声", name: "ต๊อกแต๊ก", pron: "Tok-tak (多呆)", meaning: "敲击声", gender: "偏向女生", desc: "像走路发出的可爱声音，充满童趣。" },
    { category: "叠音与可爱拟声", name: "จุ๊บจิ๊บ", pron: "Jub-jib (啾唧)", meaning: "细碎/小巧", gender: "偏向女生", desc: "形容非常小巧、嘴碎可爱的女孩子。" },
    { category: "叠音与可爱拟声", name: "ชาลี", pron: "Charlie (查理)", meaning: "查理", gender: "男女通用", desc: "洋气双音节，男女皆宜。" },
    { category: "叠音与可爱拟声", name: "โมเม", pron: "Mo-may (莫梅)", meaning: "无确切含义", gender: "偏向女生", desc: "泰国传统常见的双音节女孩名，发音温柔。" },
    { category: "叠音与可爱拟声", name: "ลูกหมู", pron: "Look-moo (路姆)", meaning: "小猪崽", gender: "男女通用", desc: "长辈最爱叫的昵称，满是宠溺。" },
    { category: "叠音与可爱拟声", name: "ลูกแก้ว", pron: "Look-kaew (路娇)", meaning: "玻璃弹珠", gender: "偏向女生", desc: "晶莹剔透，被视作掌上明珠。" },

    // === 【数字、月份与时间】 ===
    { category: "数字与时间", name: "หนึ่ง", pron: "Neung (能)", meaning: "一", gender: "男女通用", desc: "通常是家里的老大，寓意永远争第一。" },
    { category: "数字与时间", name: "สอง", pron: "Song (宋)", meaning: "二", gender: "男女通用", desc: "家里的老二，发音温和。" },
    { category: "数字与时间", name: "สาม", pron: "Sam (三)", meaning: "三", gender: "男女通用", desc: "家里的老三。" },
    { category: "数字与时间", name: "เท็น", pron: "Ten (腾)", meaning: "十(英文)", gender: "偏向男生", desc: "寓意十全十美，英文发音显洋气。" },
    { category: "数字与时间", name: "แจน", pron: "Jan (简)", meaning: "一月(缩写)", gender: "偏向女生", desc: "一月出生的女孩常用。" },
    { category: "数字与时间", name: "เมย์", pron: "May (梅)", meaning: "五月", gender: "偏向女生", desc: "非常普遍的女孩名，五月生机盎然。" },
    { category: "数字与时间", name: "จูน", pron: "June (军)", meaning: "六月", gender: "男女通用", desc: "六月宝宝专属。" },
    { category: "数字与时间", name: "ออกัส", pron: "August (奥古斯)", meaning: "八月", gender: "偏向男生", desc: "八月出生，听起来带有尊贵感。" },
    { category: "数字与时间", name: "ซันเดย์", pron: "Sunday (桑代)", meaning: "星期天", gender: "男女通用", desc: "星期天出生，阳光灿烂的一天。" },
    { category: "数字与时间", name: "ไนท์", pron: "Night (奈特)", meaning: "夜晚", gender: "偏向男生", desc: "晚上出生，带有神秘深邃的气质。" },
    { category: "数字与时间", name: "เดย์", pron: "Day (代)", meaning: "白天", gender: "偏向男生", desc: "白天出生，光明磊落。" },
    { category: "数字与时间", name: "ซัมเมอร์", pron: "Summer (夏默)", meaning: "夏天", gender: "偏向女生", desc: "热情似火，充满活力。" },
    { category: "数字与时间", name: "วินเทอร์", pron: "Winter (温特)", meaning: "冬天", gender: "男女通用", desc: "给炎热的泰国带来一丝清凉的名字。" },
    { category: "数字与时间", name: "นาว", pron: "Now (闹)", meaning: "现在", gender: "男女通用", desc: "寓意把握当下。" },
    { category: "数字与时间", name: "นิวเยียร์", pron: "New Year (纽耶)", meaning: "新年", gender: "男女通用", desc: "元旦或跨年出生的幸运儿。" },

    // === 【性格、情绪与抽象】 ===
    { category: "性格与情绪", name: "จอย", pron: "Joy (乔伊)", meaning: "欢乐", gender: "偏向女生", desc: "希望孩子一生充满喜悦。" },
    { category: "性格与情绪", name: "แฮปปี้", pron: "Happy (哈皮)", meaning: "快乐", gender: "男女通用", desc: "直白美好的祝愿。" },
    { category: "性格与情绪", name: "สไมล์", pron: "Smile (斯迈)", meaning: "微笑", gender: "偏向女生", desc: "爱笑的女孩运气不会差。" },
    { category: "性格与情绪", name: "เลิฟ", pron: "Love (乐芙)", meaning: "爱", gender: "男女通用", desc: "被爱包围的宝贝。" },
    { category: "性格与情绪", name: "ดรีม", pron: "Dream (朱琳)", meaning: "梦想", gender: "偏向女生", desc: "有梦想并为之努力。" },
    { category: "性格与情绪", name: "โฮป", pron: "Hope (霍普)", meaning: "希望", gender: "男女通用", desc: "全家的希望之光。" },
    { category: "性格与情绪", name: "เฟิร์ส", pron: "First (弗斯特)", meaning: "第一", gender: "偏向男生", desc: "事事争先，也是长子的热门名字。" },
    { category: "性格与情绪", name: "วิน", pron: "Win (温)", meaning: "赢", gender: "偏向男生", desc: "人生赢家，百战百胜。" },
    { category: "性格与情绪", name: "สมาร์ท", pron: "Smart (斯玛特)", meaning: "聪明/帅气", gender: "偏向男生", desc: "既聪明又利落。" },
    { category: "性格与情绪", name: "เคลียร์", pron: "Clear (克里尔)", meaning: "清晰", gender: "男女通用", desc: "头脑清醒，做事干净利落。" },
    { category: "性格与情绪", name: "ชิล", pron: "Chill (秋)", meaning: "放松", gender: "男女通用", desc: "性格随和，享受慢节奏生活。" },
    { category: "性格与情绪", name: "เฟรนด์", pron: "Friend (弗兰)", meaning: "朋友", gender: "男女通用", desc: "友善、人缘好。" },
    { category: "性格与情绪", name: "ลัคกี้", pron: "Lucky (拉基)", meaning: "幸运", gender: "男女通用", desc: "好运常伴左右。" },

    // === 【现代洋气 / 英文外来词深度补充】 ===
    { category: "现代洋气", name: "กัปตัน", pron: "Captain (盖普坦)", meaning: "队长/机长", gender: "偏向男生", desc: "具有领导力，男孩超热门小名。" },
    { category: "现代洋气", name: "ฮีโร่", pron: "Hero (希罗)", meaning: "英雄", gender: "偏向男生", desc: "勇敢担当，家庭的小英雄。" },
    { category: "现代洋气", name: "สกาย", pron: "Sky (斯凯)", meaning: "天空", gender: "男女通用", desc: "视野开阔，心胸广大。" },
    { category: "现代洋气", name: "โอเชี่ยน", pron: "Ocean (欧申)", meaning: "海洋", gender: "男女通用", desc: "深邃辽阔，极具现代诗意。" },
    { category: "现代洋气", name: "สเปซ", pron: "Space (斯佩斯)", meaning: "太空", gender: "偏向男生", desc: "充满对未知宇宙的探索欲。" },
    { category: "现代洋气", name: "นิกกี้", pron: "Nikki (尼基)", meaning: "Nikki", gender: "男女通用", desc: "洋气且充满活力的名字。" },
    { category: "现代洋气", name: "มาร์ค", pron: "Mark (马克)", meaning: "Mark", gender: "偏向男生", desc: "经典英文名，在泰国极受欢迎。" },
    { category: "现代洋气", name: "เจมส์", pron: "James (詹姆斯)", meaning: "James", gender: "偏向男生", desc: "带有一点绅士和贵族气息。" },
    { category: "现代洋气", name: "เควิน", pron: "Kevin (凯文)", meaning: "Kevin", gender: "偏向男生", desc: "听起来聪明乖巧的男孩名。" },
    { category: "现代洋气", name: "แอนนา", pron: "Anna (安娜)", meaning: "Anna", gender: "偏向女生", desc: "优雅、大方的经典女孩名。" },
    { category: "现代洋气", name: "เบลล่า", pron: "Bella (贝拉)", meaning: "美丽", gender: "偏向女生", desc: "因泰国顶级女星而家喻户晓的洋气名。" },
    { category: "现代洋气", name: "ญาญ่า", pron: "Yaya (雅雅)", meaning: "Yaya", gender: "偏向女生", desc: "同样是顶流女星带火的超甜美女孩名。" },
    { category: "现代洋气", name: "อลิซ", pron: "Alice (爱丽丝)", meaning: "Alice", gender: "偏向女生", desc: "充满童话色彩的梦幻名字。" },
    { category: "现代洋气", name: "เกรซ", pron: "Grace (格蕾丝)", meaning: "优雅/恩典", gender: "偏向女生", desc: "气质高雅、修养极好的女孩。" },
    { category: "现代洋气", name: "วิคเตอร์", pron: "Victor (维克多)", meaning: "胜利者", gender: "偏向男生", desc: "霸气且寓意极佳的英文名。" },
    { category: "现代洋气", name: "ซีรีส์", pron: "Series (剧集)", meaning: "系列/连续剧", gender: "偏向女生", desc: "受现代韩剧/泰剧文化影响诞生的有趣小名。" },
    { category: "现代洋气", name: "โชกุน", pron: "Shogun (幕府将军)", meaning: "将军(日文)", gender: "偏向男生", desc: "深受日本文化影响，代表权势与威风。" },
    { category: "现代洋气", name: "ไทเกอร์", pron: "Tiger (泰格)", meaning: "老虎(英文)", gender: "偏向男生", desc: "比泰语的老虎(Suea)听起来更现代国际化。" },
    { category: "现代洋气", name: "ไลออน", pron: "Lion (莱昂)", meaning: "狮子(英文)", gender: "偏向男生", desc: "国际化的王者之名。" },
    { category: "现代洋气", name: "อีฟ", pron: "Eve (伊芙)", meaning: "夏娃/前夕", gender: "偏向女生", desc: "简短、优雅，充满生命力。" },
    { category: "现代洋气", name: "กีวี่", pron: "Kiwi (奇异果)", meaning: "猕猴桃", gender: "偏向女生", desc: "酸甜可口，发音非常俏皮。" },
    { category: "现代洋气", name: "เมลอน", pron: "Melon (蜜瓜)", meaning: "甜瓜", gender: "偏向女生", desc: "日系高级水果，代表甜美多汁。" },
    { category: "现代洋气", name: "ริชชี่", pron: "Richy (里奇)", meaning: "富有的", gender: "男女通用", desc: "最直接的财富祈愿，多金又洋气。" }
];